### ISSUE TITLE
Anime episode not recognized

### ISSUE THREAD

**Issue by FireBladeNooT** [pymedusa/SickRage#1200]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:

Medusa Info:	Branch: master
Commit: c7018776ec3c169d0c17fe220651b1243bc84ea5
Version: v0.1.5.1
Python Version:	2.7.11 (default, Dec 17 2015, 13:37:18) [GCC 4.6.4 20130102 (prerelease)]
SSL Version:	OpenSSL 1.0.2e 3 Dec 2015
OS:	Linux-3.2.40-armv7l-with-glibc2.4
Locale:	en_US.UTF-8

OS: Synology

What you did:
Set a Series "Dragon Ball Super" with restriction:
- Quality: HD
- Required Words: vostfr
- Ignored Words: h265,x265,hevc,10bits,Hi10bits,10.bits,10bit,french
- Anime: Yes
- DVD Order: No
- Scene Numbering: No

What happened: It does not download the example

What you expected: Download

Logs:

**First the search:**
2016-09-26 19:01:37 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [NyaaVostfr] :: [c701877] Added RSS item: [[Mystic.Z-Team].Dragon.Ball.Super.Episode.59.v2.[VOSTFR][720p][AAC].mp4] to cache: [nyaavostfr]

2016-09-26 19:01:37 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [NyaaVostfr] :: [c701877] Parsed [Mystic.Z-Team].Dragon.Ball.Super.Episode.59.v2.[VOSTFR][720p][AAC].mp4 into release_group: Mystic.Z-Team, title: Dragon Ball Super, episode: [59], version: 2, subtitle_language: fr, screen_size: 720p, audio_codec: AAC, container: mp4, mimetype: video/mp4, type: episode, absolute_episode: [], quality: 720p HDTV, season: None

2016-09-26 19:34:12 DEBUG    SEARCHQUEUE-MANUAL-295068 :: [NyaaTorrents] :: [c701877] Found result: [Mystic Z-Team] Dragon Ball Super Episode 59 v2 [VOSTFR][720p][AAC].mp4 with 82 seeders and 29 leechers

**After I've download manually (not with sickrage):**
2016-09-26 21:00:54 DEBUG    POSTPROCESSOR :: [c701877] Parse result(release_group): WwW.DBSuper

2016-09-26 21:00:54 DEBUG    POSTPROCESSOR :: [c701877]  or Parse result(air_date): None
2016-09-26 21:00:54 DEBUG    POSTPROCESSOR :: [c701877] Parse result(episode_numbers): [59]
2016-09-26 21:00:54 DEBUG    POSTPROCESSOR :: [c701877] Parse result(season_number): None
2016-09-26 21:00:54 DEBUG    POSTPROCESSOR :: [c701877] Parse result(series_name): Dragon Ball Super

2016-09-26 21:00:54 DEBUG    POSTPROCESSOR :: [c701877] Parse result not sufficient (all following have to be set). will not save release name

2016-09-26 21:00:54 DEBUG    POSTPROCESSOR :: [c701877] Parsed [WwW.DBSuper.pw] Dragon Ball Super Episode 59 v2 [VOSTFR][720p][AAC].mp4 into release_group: WwW.DBSuper, title: Dragon Ball Super, episode: [59], version: 2, subtitle_language: fr, screen_size: 720p, audio_codec: AAC, container: mp4, mimetype: video/mp4, type: episode, absolute_episode: [], quality: 720p HDTV, season: None

2016-09-26 21:00:53 DEBUG    POSTPROCESSOR :: [c701877] Analyzing name [WwW.DBSuper.pw] Dragon Ball Super Episode 59 v2 [VOSTFR][720p][AAC].mp4

2016-09-26 21:00:53 INFO     POSTPROCESSOR :: [c701877] Processing /volume1/Download/Finish/[WwW.DBSuper.pw] Dragon Ball Super Episode 59 v2 [VOSTFR][720p][AAC].mp4 (Torrent)

**I think the episode number is not recognize as an absolute number because it contains "episode" in the torrent / file name. The version is found, the the group is not correct but I don't care because it's not filtered.

Thanks**

**Comment by medariox** [comment]
Thanks for the report. You are right, the 'Episode' is exactly the reason why the episode number doesn't get parsed as absolute (like it should). You can easily see the results of our parser with the help of a file that is located in ```medusa/tests/report_guessit.py```. Running ```python tests/report_guessit.py <episode title>``` will yield the results exactly how Medusa does, so you can compare them if you like to.

_In your case:_
```
 python tests/report_guessit.py '[WwW.DBSuper.pw] Dragon Ball Super Episode 59 v2 [VOSTFR][720p][AAC].mp4'
# guessit: 2.1.1.dev0  rebulk: 0.7.6
? [WwW.DBSuper.pw] Dragon Ball Super Episode 59 v2 [VOSTFR][720p][AAC].mp4
: release_group: WwW.DBSuper
  title: Dragon Ball Super
  episode: 59
  version: 2
  subtitle_language: fr
  screen_size: 720p
  audio_codec: AAC
  container: mp4
  mimetype: video/mp4
  type: episode
```
**No absolute number, which is wrong.**

_With 'Episode' replaced:_
```
 python tests/report_guessit.py '[WwW.DBSuper.pw] Dragon Ball Super Whatever 59 v2 [VOSTFR][720p][AAC].mp4'
# guessit: 2.1.1.dev0  rebulk: 0.7.6
? [WwW.DBSuper.pw] Dragon Ball Super Whatever 59 v2 [VOSTFR][720p][AAC].mp4
: release_group: WwW.DBSuper
  title: Dragon Ball Super Whatever
  episode: 59
  absolute_episode: 59
  version: 2
  subtitle_language: fr
  screen_size: 720p
  audio_codec: AAC
  container: mp4
  mimetype: video/mp4
  type: episode
```
**Absolute number is there, correctly parsed.**

So that 'Episode' is indeed the issue. As you can imagine this is a bit of an edge case. We will try to fix this, marking it as bug for now.

**Comment by ratoaq2** [comment]
Fixed by #1212

**Comment by FireBladeNooT** [comment]
Thanks a lot ;)

**Comment by FireBladeNooT** [comment]
Hi again,
issue not solved,
2016-10-07 19:08:43 INFO     Thread-24 :: [2697d37] Not enough information to determine what episode this is. Quitting post-processing
2016-10-07 19:08:43 DEBUG    Thread-24 :: [2697d37] Unable to match Finish [Miracle] Dragon Ball Super Episode 55 [VOSTFR][720p].mp4 to a show in your database. Parser result: title: Finish, release_group: Miracle, episode_title: Dragon Ball Super, episode: [55], subtitle_language: fr, screen_size: 720p, container: mp4, mimetype: video/mp4, type: episode, absolute_episode: [], quality: Unknown, season: None
2016-10-07 19:08:42 DEBUG    Thread-24 :: [2697d37] Analyzing name Finish [Miracle] Dragon Ball Super Episode 55 [VOSTFR][720p].mp4

I've version 2016-10-05 - 0.1.6

The parser thinks "series name" is "episode name" :(
