### ISSUE TITLE
Newznab search categories are not retained through restarts

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#415]
@p0psicles its a JS issue that need to be fixed

Issue from old repo with details
https://github.com/SickRage/sickrage-issues/issues/1215

**Comment by p0psicles** [comment]
This should fix it: https://github.com/pymedusa/SickRage/pull/429

**Comment by p0psicles** [comment]
@gersilex could you test if this fixes it for you?

**Comment by gersilex** [comment]
@p0psicles I tested it on `develop` right now, with my old and a completely blank config. Looks like the problem still persists.

For reference, the reproduction steps:

Open search provider settings
choose "NZBGeek" Provider in advanced settings
select CatIDs 5020, 5030, 5040
Update Categories
Save to config (sickrage successfully asks for all 3 CatIDs on API requests)
Restart SickRage with cleanly via menu (sickrage only queries the default 5030 and 5040 CatIDs again, settings reflect this behaviour)

My Sickrage is up and running now again, sorry for the delay guys.
